### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by wshanks** [ffledgling/dactyl-build#1]
Thanks for doing this. I had been thinking about doing something similar.

One thing you might look into is if it is possible to host an `update.rdf` file on GitHub that will meet Firefox's criteria for auto-updating addons. Then you could patch Pentadactyl before building so that it will check here for updates. I think this is possible but setting it up seems a little tricky from the documentation online (you have to set up the crypto keys correctly). I will look into it myself if I find time.

By the way, there is another workaround to the maxVersion problem -- disabling version compatibility checking. The checkCompatibility addon by Kris (author of Pentadactyl) can do this.

**Comment by ffledgling** [comment]
I would love to try setting this up, but I'm not sure I can do something like that without explicit permission from the project (Pentadactyl) owners.

**Comment by wshanks** [comment]
Pentadactyl uses the MIT license so the developers have already given their permission in that sense, but I agree that it would better to hear something from them first.

In the dactyl Google Code issue, you said that you tried contacting them. I don't suppose that you have heard anything from @kmaglione or @dkearns yet? I have tried asking on IRC but haven't seen the developers post anything in the #pentadactyl channel.

I have been following the issue tracker and mailing list for Pentadactyl (you probably have too) and recently there has been a growing number of people asking how they can help with the project and what its future is. The builds you have set up here are a nice stopgap, but I think we need something more visible and user friendly to prevent those users from giving up on Pentadactyl and drifting away. Hopefully we can get a response from the developers and find a way to continue distributing Pentadactyl that is easy for everyone.

**Comment by ffledgling** [comment]
I haven't heard anything from them yet. I've seen people bring up the issue on #pentadactyl, but haven't seen a straight response to the queries, although I do remember John-Galt saying that he's experimenting with a new build system somewhere. I also see that the nightlies are back up on 5digits.org.

I haven't been following the mailing list, but I do lurk around in the IRC channel and check the issue tracker periodically. I think I may have already mentioned this on the code.google.com issue and I did mention it to @kmagilone in the mail I sent him that I'm willing to help with the process if it's required at any step, but until I have some sort of response from the devs, I'll just let this stop-gap sit until it's outlived it's usefulness (Or more optimistically, till something better comes along).

**Comment by wshanks** [comment]
Yes, there has been some action in the last week so these builds have not been as necessary once again. I would keep them going though because the official nightlies stopped again for a day on the 25th. I think Kris restarted them manually after someone in the IRC was asking about the nightly being broken with Firefox 36, but they could stop again.

I think the developers are really busy and just have enough time to keep the project updated but not to track the mailing list or respond to requests. I'm not sure why the repo is mirrored on GitHub now. I had the impression that they kept the repo on Google Code partly because they wanted it to be slightly difficult to submit patches so that they don't have to spend time reviewing patches that don't meet their standards.
